project:
  type: website
  output-dir: docs

website:
  title: "Philip S. Boonstra"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: teaching.qmd
        text: Teaching
      - href: files/BoonstraCV.pdf
        text: CV
      - href: https://scholar.google.com/citations?user=GiaDuZwAAAAJ&hl=en
        icon: mortarboard-fill
      - href: https://github.com/psboonstra
        icon: github
      - href: https://www.linkedin.com/in/phil-boonstra-5b9b792a7/
        icon: linkedin
      
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

